# Generated by Django 2.2.2 on 2020-10-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Faculty', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=20)),
                ('Fee', models.IntegerField()),
                ('Duration', models.CharField(max_length=30)),
            ],
        ),
    ]
