# Generated by Django 2.2.2 on 2020-10-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201015_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Contact', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
