# Generated by Django 2.2.2 on 2020-10-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enrolldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolldetails',
            name='Course_id',
        ),
        migrations.AddField(
            model_name='enrolldetails',
            name='Course_name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
