# Generated by Django 2.2.2 on 2020-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201019_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
